baseURL = 'https://lazulite.app'
languageCode = 'en-us'
title = 'Lazulite App'
theme = "lazulite"

# Allow raw HTML in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[params.social]]
key = 0
name = "email"
url = "mailto:lazulite.app@example.com"
#icon = "fa-solid fa-envelope"

[menu]
  [[menu.header]]
    name = "Privacy Policy"
    weight = 0
    url = "/privacy"
  [[menu.header]]
    name = "FAQ"
    weight = 1
    url = "/faq"
#  [[menu.header]]
#    name = "posts"
#    weight = 0
#    url = "/posts"

[params]
footerHtml = 'Lazulite App for Android'
readingTime = false  # Show reading time on post page
published = false  # Show published data on post page
